name: Continuous Integration

on:
  push:
    branches: [ main ] # the branch we want this to run on

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install
    - run: yarn test

